### ISSUE TITLE
LDAP: Could not login on the server - django_auth_ldap: create_user()

### ISSUE THREAD

**Issue by brunomaso1** [cvat-ai/cvat#9382]
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Configure LDAP connection (as showed in the docs).
2. Try to login...

Error ->

![Image](https://github.com/user-attachments/assets/3fa41a07-9474-40a4-bb50-f23e31330aad)

### Expected Behavior

Should have logged in.

### Possible Solution

Possible issue when migrating from version 2.32.0 to 2.33.0

### Context

After migrating from version 2.28.0 to 2.35.0, I tried logging in with my usual credentials and encountered the same issue.

The full error displayed is as follows:
```log
cvat_server                  | [2025-05-01 15:45:51,772] WARNING django_auth_ldap: create_user() missing 2 required positional arguments: 'created' and 'raw' while authenticating cvat.admin                                                                                                                                                                                 
cvat_server                  | 
cvat_server                  | 2025-05-01 15:45:52,187 DEBG 'uvicorn-0' stderr output:                                                                                                 
cvat_server                  | [2025-05-01 15:45:51,918] ERROR django.request: Internal Server Error: /api/auth/login
cvat_server                  | Traceback (most recent call last):                                                                                                                      
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler                                                            
cvat_server                  |     raise exc_info[1]                                                                                                                                   
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner                                                    
cvat_server                  |     response = await get_response(request)                                                                                                              
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async                                          
cvat_server                  |     response = await wrapped_callback(                                                                                                                  
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__                                                                  
cvat_server                  |     ret = await asyncio.shield(exec_coro)                                                                                                               
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run                                                     
cvat_server                  |     result = self.fn(*self.args, **self.kwargs)
traefik                      | {"ClientHost":"172.18.0.8","DownstreamContentSize":145,"DownstreamStatus":500,"Duration":1154018505,"RequestHost":"cvat.picudo-rojo-desarrollo.org","RequestMethod":"POST","RequestPath":"/api/auth/login?org=","RequestPort":"-","RequestProtocol":"HTTP/1.1","RouterName":"cvat@docker","StartUTC":"2025-05-01T15:45:51.04616834Z","level":"info","msg":"","time":"2025-05-01T15:45:52Z"}
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
cvat_server                  |     return func(*args, **kwargs)                                                                                                                        
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view                                               
cvat_server                  |     return view_func(*args, **kwargs)                                                                                                                   
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
cvat_server                  |     return self.dispatch(request, *args, **kwargs)                                                                                                      
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper                                                        
cvat_server                  |     return bound_method(*args, **kwargs)                                                                                                                
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper                         
cvat_server                  |     return view(request, *args, **kwargs)                                                                                                               
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 48, in dispatch                                                             
cvat_server                  |     return super().dispatch(*args, **kwargs)                                                                                                            
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch                                                          
cvat_server                  |     response = self.handle_exception(exc)                                                                                                               
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception                                                  
cvat_server                  |     self.raise_uncaught_exception(exc)                                                                                                                  
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception                                          
cvat_server                  |     raise exc                                                                                                                                           
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch                                                          
cvat_server                  |     response = handler(request, *args, **kwargs)                                                                                                        
cvat_server                  |   File "/home/django/cvat/apps/iam/views.py", line 105, in post                                                                                         
cvat_server                  |     self.login()                                                                                                                                        
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 66, in login                                                                
cvat_server                  |     self.user = self.serializer.validated_data['user']                                                                                                  
cvat_server                  |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 267, in validated_data                                              
cvat_server                  |     raise AssertionError(msg)                                                                                                                           
cvat_server                  | AssertionError: You must call `.is_valid()` before accessing `.validated_data`.                                                                         
cvat_server                  |                                                                                                                                                         
cvat_server                  | 2025-05-01 15:45:52,195 DEBG 'uvicorn-0' stdout output:                                                                                                 
cvat_server                  | [2025-05-01 15:45:52,194] INFO:     172.18.0.8:0 - "POST /api/auth/login?org= HTTP/1.0" 500 Internal Server Error
```

I had no issues in version 2.28.0.

However, I was able to trace the issue back to version 2.33.0. I tested it in version 2.32.0 and it worked perfectly, but in version 2.33.0 it no longer worked.

Specifically, the issue may be in `cvat/apps/iam/signals.py`.

The following was introduced in version 2.33.0:

```python
elif settings.IAM_TYPE == "LDAP":

    def create_user(sender, created: bool, raw: bool, user=None, ldap_user=None, **kwargs):
        if created and raw:
            return
```

My overlay (that work's on v2.32.0) settings is:
```python
# Overlaying production
from cvat.settings.production import *

# Custom code below
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfUniqueNamesType

if os.environ.get("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")

try:
    CVAT_LDAP_USER = os.environ["CVAT_LDAP_USER"]
    CVAT_LDAP_PASSWORD = os.environ["CVAT_LDAP_PASSWORD"]
except KeyError:
    print("Environment variable does not exist")

# Notify CVAT that we are using LDAP authentication
IAM_TYPE = "LDAP"

# Talking to the LDAP server
AUTH_LDAP_SERVER_URI = os.environ.get("AUTH_LDAP_SERVER_URI", "ldap://lldap:3890")  # IP Addresses also work
ldap.set_option(ldap.OPT_REFERRALS, 0)


_BASE_DN = "DC=localhost,DC=local"
_PEOPLE_OU = "OU=people"
_GROUP_OU = "OU=groups"
_PEOPLE_DN = "%s,%s" % (_PEOPLE_OU, _BASE_DN)
_GROUP_DN = "%s,%s" % (_GROUP_OU, _BASE_DN)

# Authenticating with the LDAP server
AUTH_LDAP_BIND_DN = "CN=%s,%s" % (CVAT_LDAP_USER, _PEOPLE_DN)
AUTH_LDAP_BIND_PASSWORD = CVAT_LDAP_PASSWORD

AUTH_LDAP_USER_SEARCH = LDAPSearch(_BASE_DN, ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    _GROUP_DN, ldap.SCOPE_SUBTREE, "(objectClass=groupOfUniqueNames)"
)

print("AUTH_LDAP_GROUP_SEARCH", AUTH_LDAP_GROUP_SEARCH)
print("AUTH_LDAP_USER_SEARCH", AUTH_LDAP_USER_SEARCH)

# Mapping Django field names to FreeIPA attributes
AUTH_LDAP_USER_ATTR_MAP = {
    "user_name": "uid",
    "first_name": "first_name",
    "last_name": "last_name",
    "email": "mail",
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True

# Cache group memberships for an hour to minimize LDAP traffic
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600
AUTH_LDAP_AUTHORIZE_ALL_USERS = False

# Group Management
AUTH_LDAP_GROUP_TYPE = GroupOfUniqueNamesType(name_attr="cn")

# Register Django LDAP backend
AUTHENTICATION_BACKENDS += ["django_auth_ldap.backend.LDAPBackend"]

# Map FreeIPA groups to Django/CVAT groups.
AUTH_LDAP_ADMIN_GROUPS = [
    "CN=cvat_admins,%s" % _GROUP_DN,
]
AUTH_LDAP_WORKER_GROUPS = [
    "CN=cvat_workers,%s" % _GROUP_DN,
]
AUTH_LDAP_USER_GROUPS = [
    "CN=cvat_users,%s" % _GROUP_DN,
]

DJANGO_AUTH_LDAP_GROUPS = {
    "admin": AUTH_LDAP_ADMIN_GROUPS,
    "user": AUTH_LDAP_USER_GROUPS,
    "worker": AUTH_LDAP_WORKER_GROUPS,
}
```

### Environment

```Markdown
- CVAT version: 2.35.0
- Docker compose
- LLDAP
```
