### PR TITLE
fix types.py ImportError in generate_manifest

### PR DESCRIPTION
**Pull request by archibald1418**
### Motivation and context

 CI-Nightly run on the branch
https://github.com/cvat-ai/cvat/actions/runs/17827948814

All Nightlies `unit_testing` workers fail with following 17 tests related to tasks in cloud storage

Test Logs:

> ========================== short test summary info ============================
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_directories_and_excluded_files[-True-True-server_files3-None-6-2]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_directories_and_excluded_files[-True-True-server_files4-None-6-2]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_directories_and_excluded_files[-True-True-server_files5-server_files_exclude5-2-2]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_directories_and_predefined_sorting[-server_files0-expected_result0-True-2]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[manifest.jsonl-*-True-3-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[manifest.jsonl-test/*-True-3-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[manifest.jsonl-test/sub*1.jpeg-True-1-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[manifest.jsonl-*image*.jpeg-True-3-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[manifest.jsonl-wrong_pattern-True-0-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[abc_manifest.jsonl-[a-c]*.jpeg-False-2-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[abc_manifest.jsonl-[d]*.jpeg-False-1-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_file_pattern[abc_manifest.jsonl-[e-z]*.jpeg-False-0-1]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_and_retrieve_data[1--natural-True-True]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_and_retrieve_data[1--predefined-True-True]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_and_retrieve_data[1--lexicographical-True-True]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_directories_and_default_bucket_prefix[-test/sub_1/img_0-1-server_files0-True-2]
> FAILED tests/python/rest_api/test_task_data.py::TestPostTaskData::test_create_task_with_cloud_storage_directories_and_default_bucket_prefix[-test/sub_1/-3-server_files0-True-2]
> = 17 failed, 2036 passed, 39 skipped, 1 xfailed, 1 warning in 1771.21s (0:29:31) =

All related to `generate_manifest` calling `docker run` inside test cases
Trace shows how python confuses built-in `types` with `dataset_manifest/types.py` leading to circular import

> ----------------------------- Captured stdout call -----------------------------
> Traceback (most recent call last):
>   File "/home/django/utils/dataset_manifest/create.py", line 8, in <module>
>     import argparse
>   File "/usr/lib/python3.10/argparse.py", line 89, in <module>
>     import re as _re
>   File "/usr/lib/python3.10/re.py", line 124, in <module>
>     import enum
>   File "/usr/lib/python3.10/enum.py", line 2, in <module>
>     from types import MappingProxyType, DynamicClassAttribute
>   File "/home/django/utils/dataset_manifest/types.py", line 6, in <module>
>     from typing import Protocol
>   File "/usr/lib/python3.10/typing.py", line 25, in <module>
>     import contextlib
>   File "/usr/lib/python3.10/contextlib.py", line 6, in <module>
>     from functools import wraps
>   File "/usr/lib/python3.10/functools.py", line 22, in <module>
>     from types import GenericAlias
> ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/django/utils/dataset_manifest/types.py)
> 

### How to reproduce on develop

- With test cluster
`docker run --rm -u root:root --entrypoint python cvat/server:dev utils/dataset_manifest/create.py --help`
crashes with the same exception

- Locally
```
cd utils/dataset_manifest
python3 -m venv .env && source .env/bin/activate
python create.py
```

First bad commit on `develop` contained google-cloud-storage bump to version 3+

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by archibald1418** [comment]
Another possible fix was discussed in #9826 - renaming the `types.py` inside `dataset_manifest`

**Comment by SpecLad** [comment]
This workaround isn't great, because it does nothing for people who want to run `create.py` independently of CVAT. `google-cloud-storage` is not included in `utils/dataset_manifest/requirements.in`, and it would be silly to put it there.

Also, I'm not sure what was the point of submitting this when #9826 had already been merged yesterday?

**Comment by archibald1418** [comment]
#9826 didin't fix anything, the bug is still reproducing - both in container and locally
And after the fix, CI-Nightly still fails. It failed on develop today, and still failing on this branch

**Comment by archibald1418** [comment]
### Before renaming

1. https://github.com/cvat-ai/cvat/actions/runs/17837304684 - failed

2. 
```
docker run --rm -u root:root --entrypoint python cvat/server:dev utils/dataset_manifest/create.py --help
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/django/utils/dataset_manifest/types.py)
```

3. 
```
cd utils/dataset_manifest
python3 -m venv .env && source .env/bin/activate
python create.py
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/django/utils/dataset_manifest/types.py)
```

**Comment by archibald1418** [comment]
### After renaming

1. https://github.com/cvat-ai/cvat/actions/runs/17838596024 - passed

2.
```bash
docker run --rm -u root:root --entrypoint python cvat/server:dev utils/dataset_manifest/create.py --help
usage: create.py [-h] [--force] [--output-dir OUTPUT_DIR]
                 [--sorting {lexicographical,natural,predefined,random}]
                 source
```
(no `ImportError`)

3.
```bash
cd utils/dataset_manifest
python3 -m venv .env && source .env/bin/activate
python create.py
Traceback (most recent call last):
  File "/home/oleg/app_cvat_ai/cvat_enterprise/cvat/utils/dataset_manifest/create.py", line 19, in <module>
    from dataset_manifest.core import ImageManifestManager, VideoManifestManager
  File "/home/oleg/app_cvat_ai/cvat_enterprise/cvat/utils/dataset_manifest/__init__.py", line 4, in <module>
    from .core import ImageManifestManager, VideoManifestManager, is_manifest
  File "/home/oleg/app_cvat_ai/cvat_enterprise/cvat/utils/dataset_manifest/core.py", line 19, in <module>
    import av
ModuleNotFoundError: No module named 'av'
``` 
(expected, local .env doesn't have av, but no `ImportError`)

**Comment by zhiltsov-max** [comment]
I think the issue is that in the reproducing example you're running commands from the dataset_manifest directory. Python adds the current directory into pythonpath.

**Comment by archibald1418** [comment]
[builtins_test.zip](https://github.com/user-attachments/files/22415788/builtins_test.zip)
Please try several python versions with `tox`, do any of them may print `TYPES` ?

**Comment by zhiltsov-max** [comment]
How this is related to the topic?

**Comment by archibald1418** [comment]
What solution do you suggest we implement?

**Comment by zhiltsov-max** [comment]
A rough solution could be rewriting the script header like this:

```python
...
# SPDX-License-Identifier: MIT

import os
import sys

if __name__ == "__main__":
    # fix types.py import

    # Remove the script directory from the path, it can be appended by the interpreter
    script_dir = os.path.dirname(os.path.abspath(__file__))
    try:
        sys.path.remove(script_dir)
    except ValueError:
        pass

    # Make the component visible as dataset_manifest module
    base_dir = os.path.dirname(script_dir)
    sys.path.append(base_dir)

import argparse
import re
from glob import glob

from tqdm import tqdm

...
```

**Comment by SpecLad** [comment]
> Python adds the current directory into pythonpath.

Not when you run a script. In this case, it's the script's directory that is added. See the second paragraph in <https://docs.python.org/3/library/sys_path_init.html>.

File: utils/dataset_manifest/create.py [hunk 1]
```diff
@@ -5,21 +5,31 @@
...
 if __name__ == "__main__":
     # fix types.py import
-    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
+
+    # Remove the script directory from the path, it can be appended by the interpreter
+    script_dir = os.path.dirname(os.path.abspath(__file__))
+    try:
+        sys.path.remove(script_dir)
+    except ValueError:
+        print("warning: {script_dir} was not found in sys.path")
```
Comment (zhiltsov-max) [inline utils/dataset_manifest/create.py]:
```suggestion
        print(f"warning: {script_dir} was not found in sys.path")
```

**Comment by archibald1418** [comment]
@zhiltsov-max could we skip generate_github_pages since it's not a user-facing change?

**Comment by zhiltsov-max** [comment]
Do you mean if it's allowed to cancel a CI run manually or you want to make some CI changes to skip documentation updates in some cases?

**Comment by archibald1418** [comment]
I mean it was failing in the checks, I asked if we could ignore it and still merge even if it fails
UPD: now it's green so I guess it doesn't matter

**Comment by zhiltsov-max** [comment]
We can merge if we know that the error is likely not on the CVAT side - e.g. a persistent random npm error like in this case.

File: utils/dataset_manifest/create.py [hunk 2]
```diff
@@ -5,21 +5,31 @@
...
 if __name__ == "__main__":
     # fix types.py import
-    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
+
+    # Remove the script directory from the path, it can be appended by the interpreter
+    script_dir = os.path.dirname(os.path.abspath(__file__))
+    try:
+        sys.path.remove(script_dir)
+    except ValueError:
+        print(f"warning: {script_dir} was not found in sys.path")
```
Comment (zhiltsov-max) [inline utils/dataset_manifest/create.py]: What is the point of this message for the users?
