### ISSUE TITLE
make_client() not working in python SDK >2.29.0

### ISSUE THREAD

**Issue by edalholt** [cvat-ai/cvat#9169]
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When using
`make_client(host=BASE_URL, credentials=(CVAT_USER, CVAT_PASSWORD))`
I get the exception:
`About._from_openapi_data() missing 2 required positional arguments: 'logo_url' and 'subtitle'`

The cvat-sdk seems to work normally in version 2.29.0.
However i get this error when using version 2.30.0 and 2.31.0.
I have updated to the newest CVAT server, but the error still occur.

### Context

Full stack trace:

self.client = make_client(host=BASE_URL, credentials=(CVAT_USER, CVAT_PASSWORD))
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/core/client.py", line 341, in make_client
  client = Client(url=url)
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/core/client.py", line 97, in __init__
  self.check_server_version()
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/core/client.py", line 238, in check_server_version
  server_version = self.get_server_version()
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/core/client.py", line 272, in get_server_version
  (about, _) = self.api_client.server_api.retrieve_about()
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/api/server_api.py", line 402, in retrieve_about
  return self.retrieve_about_endpoint.call_with_http_info(**kwargs)
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/api_client.py", line 1075, in call_with_http_info
  return self.api_client.call_api(
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/api_client.py", line 503, in call_api
  return self.__call_api(**params)
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/api_client.py", line 288, in __call_api
  return_data = self.deserialize(
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/api_client.py", line 395, in deserialize
  deserialized_data = validate_and_convert_types(
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/model_utils.py", line 1594, in validate_and_convert_types
  converted_instance = attempt_convert_item(
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/model_utils.py", line 1477, in attempt_convert_item
  return deserialize_model(input_value, valid_class,
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/model_utils.py", line 1391, in deserialize_model
  return model_class._new_from_openapi_data(**kw_args)
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
  return fn(_self, *args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/model_utils.py", line 379, in _new_from_openapi_data
  return cls._from_openapi_data(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
  return fn(_self, *args, **kwargs)
 TypeError: About._from_openapi_data() missing 2 required positional arguments: 'logo_url' and 'subtitle'

### Environment

```Markdown
CVAT version:
commit 6cefd3fe0025d58236de9db38f12622d889518e4 (HEAD -> develop, origin/develop, origin/HEAD)

Docker version 28.0.1, build 068a01e

Ubuntu 24.04.2 LTS
```
